### ISSUE TITLE
make_gf_view_from_g_and_tail no longer working

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#242]
Hi,
The following piece of code:
```
#include <triqs/gfs.hpp>
using namespace triqs::gfs;
int main(){
 double beta = 1;
 auto g = gf<imfreq, matrix_valued, no_tail>{{beta, Fermion, 100},{1,1}};
 tail t(1,1);
 auto gwt = make_gf_view_from_g_and_tail(g,t);
}
```
which used to work in the 1.1 version, does not compile in 1.2, with the following error message:
```
In function ‘int main()’:
/home/tayral/Work/TRIQS_master/source/triqs/test/triqs/gfs/thomas/basic_manipulations_3.cpp:17:45: error: no matching function for call to ‘make_gf_view_from_g_and_tail(triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::nothing>&, triqs::gfs::tail&)’
  auto gwt = make_gf_view_from_g_and_tail(g,t);
                                             ^
/home/tayral/Work/TRIQS_master/source/triqs/test/triqs/gfs/thomas/basic_manipulations_3.cpp:17:45: note: candidate is:
In file included from /home/tayral/Work/TRIQS_master/source/triqs/triqs/gfs/imtime.hpp:25:0,
                 from /home/tayral/Work/TRIQS_master/source/triqs/triqs/gfs.hpp:27,
                 from /home/tayral/Work/TRIQS_master/source/triqs/test/triqs/gfs/thomas/basic_manipulations_3.cpp:1:
/home/tayral/Work/TRIQS_master/source/triqs/triqs/gfs/./local/no_tail.hpp:58:48: note: template<class Variable, class Target, class S, class Evaluator, bool V, bool C> triqs::gfs::gf_view<Variable, Target, triqs::gfs::tail, Evaluator, C> triqs::gfs::make_gf_view_from_g_and_tail(const triqs::gfs::gf_impl<Variable, Target, triqs::gfs::nothing, Evaluator, V, C>&, triqs::gfs::tail_view)
  gf_view<Variable, Target, tail, Evaluator, C> make_gf_view_from_g_and_tail(gf_impl<Variable, Target, no_tail, Evaluator, V, C> const &g,
                                                ^
/home/tayral/Work/TRIQS_master/source/triqs/triqs/gfs/./local/no_tail.hpp:58:48: note:   template argument deduction/substitution failed:
/home/tayral/Work/TRIQS_master/source/triqs/test/triqs/gfs/thomas/basic_manipulations_3.cpp:17:45: note:   couldn't deduce template parameter ‘S’
  auto gwt = make_gf_view_from_g_and_tail(g,t);
```
Any idea how to fix this?
Thanks
