### ISSUE TITLE
Python header not found during make

### ISSUE THREAD

**Issue by paulwu123** [TRIQS/triqs#662]
Hi, I'm trying to install TRIQS, so I followed the installation steps described here: https://triqs.github.io/triqs/1.4/install.html. After several problems that I could fix, I'm stuck at compiling the code with make (step 4).
This is the error message:

> [  0%] Built target gtest
> [  0%] Building CXX object triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/h5/simple_read_write.cpp:21:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/h5/./simple_read_write.hpp:22:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/array.hpp:22:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/utility/first_include.hpp:23:
> In file included from /usr/local/bin/include/cpp2py.hpp:8:
> /usr/local/bin/include/./cpp2py/pyref.hpp:2:10: fatal error: 'Python.h' file not
>       found
> #include <Python.h>
>          ^~~~~~~~~~
> 1 error generated.
> make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o] Error 1
> make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
> make: *** [all] Error 2

Obviously some headers are not found, but I don't know how to fix this without changing all files of TRIS by hand, where this problem occurs. (my OS is macOS 10.14.1)
Thanks a lot, Paul.

**Comment by amoutenet** [comment]
Hi Paul,

I think @parcollet will know how to fix this (by the way this is the same error message I get when trying to compile Corentin's code).
This should be better documented as I've seen this error multiple times (right now I don't remember how to solve it, but it's been a recurrent problem).

Best,
Alice

**Comment by amoutenet** [comment]
Paul, apart from this, do you know which version of TRIQS you're trying to install? The installation steps you provided are the ones for the 1.4 version, but if you downloaded the master branch recently, the version is now 2.0 and you should follow the steps provided here:
https://triqs.github.io/triqs/master/install.html

**Comment by paulwu123** [comment]
I'm installing version 2.0. Following the steps of provided for this version yields the same error. I fixed this issue now using:

export CPLUS_INCLUDE_PATH=/Library/Frameworks/Python.framework/Headers

But then the next problem occurs:

> [  0%] Built target gtest
> [  0%] Building CXX object triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/h5/simple_read_write.cpp:21:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/h5/./simple_read_write.hpp:22:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/array.hpp:25:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/impl/indexmap_storage_pair.hpp:23:
> In file included from /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/indexmaps/cuboid/../../impl/../storages/shared_block.hpp:25:
> /Users/username/Desktop/Cpptest/triqs.src/triqs/arrays/indexmaps/cuboid/../../impl/../storages/./mem_block.hpp:32:10: fatal error: 
>       'numpy/arrayobject.h' file not found
> #include <numpy/arrayobject.h>
>          ^~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o] Error 1
> make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
> make: *** [all] Error 2

**Comment by amoutenet** [comment]
Hi, 

This really looks like the kind of problems we have when updating from 1.4 / 2.0. Could you check the following points:
- did you properly source the cpp2pyvars.sh file as indicated in the installation steps?
- could you clean the build and install repos both for triqs and restart the installation? If you didn't remove all files from those repos after updating the files, your system might try to update the existing files and run in all sorts of problems.

These two points usually solve these problems. The export you added shouldn't be needed.

Alice

**Comment by paulwu123** [comment]
After cleaning up everything and starting a new installation, it works now.
Thanks a lot for your help!

**Comment by dmantadakis** [comment]
Dear All,

I installed the unstable branch and I run into the same problem (Python.h not found) when trying to build a standalone c++ executable using the **CMakeLists.txt** and **arrays.cpp** that I found at 

[https://github.com/TRIQS/tutorials/tree/master/TRIQSPaperExamples/c%2B%2B](url)

The same error occurs when trying to build against the master branch too. Any help would be appreciated.

Best,
Danny

**Comment by Wentzell** [comment]
The python headers will only be found if you actually link your CMake Targets against the
exported triqs target!

```cmake
find_package(TRIQS 2.0 Required)
find_package(Cpp2Py Required)

target_link_libraries(my_target triqs)
```
