### ISSUE TITLE
[gfs] issue with expression with negative Matsubara freqs and matrix_valued fcts

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#275]
The following code snippet:
```
template <typename Function, typename Mesh>
 void print_all(Function const &f, Mesh const &m)  {
   for (auto const &x : m) std::cout << dcomplex(x) << "\t" << f(x) << std::endl;
 }

int main(){
 auto g_half = gf<imfreq,matrix_valued> {{1, Fermion, 3, true},{1,1}};
 auto g_full = gf<imfreq,matrix_valued> {{1, Fermion, 6, false},{1,1}};

 placeholder<0> om_;
 g_half(om_) << 1/(om_+3);

 for(auto const & w : g_full.mesh())
  std::cout << dcomplex(w) << "\t" << g_half(w)(0,0) << std::endl;
 std::cout << std::endl;

 print_all(om_ >> 1*g_half(om_)(0,0), g_full.mesh());
}
```
prints:
```
0	-15.708	0.0117307	0.0614216
0	-9.42478	0.0306666	0.0963418
0	-3.14159	0.158986	0.16649
0	3.14159	0.158986	-0.16649
0	9.42478	0.0306666	-0.0963418
0	15.708	0.0117307	-0.0614216

0	-15.708	1.67846e-316	0.0614216
0	-9.42478	1.67846e-316	0.0963418
0	-3.14159	1.67846e-316	0.16649
0	3.14159	0.158986	-0.16649
0	9.42478	0.0306666	-0.0963418
0	15.708	0.0117307	-0.0614216
```
The second way of printing (using the function print_all) gives an erroneous real part for negative Matsubara frequencies. Any idea why this happens? (this code works in 1.3)
Thanks

**Comment by tayral** [comment]
any idea here? thanks!

**Comment by krivenko** [comment]
Compilation of the new test fails when I try to build from `dev` branch:
```
/afs/physnet.uni-hamburg.de/users/th1_li/ikrivenk/TRIQS/libs.git/test/triqs/gfs/issue275.cpp:5:58: error: use of undeclared identifier 'matsubara_mesh_opt'
 auto g_half = gf<imfreq,matrix_valued> {{1, Fermion, 3, matsubara_mesh_opt::positive_frequencies_only},{1,1}};
```

**Comment by parcollet** [comment]
Must be a mistake, this change was supposed to begin g(tau) complex.
